api_platform:
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
  formats:
    json: ['application/json']
    jsonld: ['application/ld+json']
    html: ['text/html']
  #  multipart: ['multipart/form-data']
