api_platform:
  defaults:
    pagination_enabled: false
  title: 'API - Country Visitor'
  description: 'API for learning - Country Visitor'
  version: '1.0.0'
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
