lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    api_platform:
        check_path: /auth
        username_path: email
        password_path: password
    # Set the token expiration time (in seconds)
    token_ttl: 360000 # 1 hour (adjust the value as per your requirements)
