# api/config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        media_object:
            uri_prefix: /uploads/flags
            upload_destination: '%kernel.project_dir%/public/uploads/flags'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
